### ISSUE TITLE
Cloud Nuke is not able to remove HTTP API Gateways

### ISSUE THREAD

**Issue by rafaljanicki** [gruntwork-io/cloud-nuke#362] opened 2022-09-22 08:56 UTC
CN correctly identifies API Gateways to remove, but fails when it tries to:

```
[cloud-nuke] time="2022-09-21T10:45:41Z" level=info msg="Deleting Api Gateways (v1) in region us-east-1"
[cloud-nuke] time="2022-09-21T10:45:41Z" level=error msg="[Failed] Error deleting API Gateway (v1) <API_ID> in us-east-1"
[cloud-nuke] time="2022-09-21T10:45:41Z" level=error msg="[Failed] NotFoundException: Invalid API identifier specified <ACCOUNT_ID>:<API_ID>"
```

Cloud Nuke version: 0.19.0

**Comment by zackproser** [comment] 2022-09-27 19:01
Thanks for your report @rafaljanicki - could you please check to see if release v0.19.1 resolves this issue for you?

**Comment by sapenteng** [comment] 2022-10-21 21:34
Hi, @zackproser and @rafaljanicki , I can confirm that CN can delete APIs but my only issue is that it doesn't correctly identify all API Gateways present in an account. I had over 200 Api in an account in one region, but CN only identified 24 in that region. Is this a behavior anyone has noticed? Not sure what I'm missing. Any ideas will be much appreciated. Thank you.
`cloud-nuke inspect-aws --resource-type apigateway --resource-type apigatewayv2`

**Comment by zackproser** [comment] 2022-10-24 18:12
I'm going to close this ticket out because I'm confident the issue described in the first post has been fixed.

Hi @sapenteng, could I ask you to please open a separate issue for the problem you've observed with the `inspect` functionality? It will keep things organized and make it easier for us to find and work on your issue in the future. Thanks!

**Closed by zackproser** 2022-10-24 18:12 UTC
Labels: bug, p:needs triage
