### ISSUE TITLE
time.ParseError when trying delete ECS Cluster

### ISSUE THREAD

**Issue by hposca** [gruntwork-io/cloud-nuke#182] opened 2021-03-15 21:41 UTC
Trying to execute `cloud-nuke aws --config example.yaml --exclude-resource-type s3 --exclude-resource-type iam` on our `sandbox` account encountered this error:

```
...
INFO[2021-03-15T14:37:19-07:00] Checking region [14/18]: us-east-1
ERRO[2021-03-15T14:37:24-07:00] Error parsing the timestamp into a `RFC3339` Time format
ERRO[2021-03-15T14:37:24-07:00] Error parsing the `cloud-nuke-first-seen` tag for ECS cluster with ARN arn:aws:ecs:us-east-1:353720269506:cluster/ecs-prod
ERRO[2021-03-15T14:37:24-07:00] Error getting the `cloud-nuke-first-seen` tag for ECS cluster with ARN arn:aws:ecs:us-east-1:353720269506:cluster/ecs-prod
ERRO[2021-03-15T14:37:24-07:00] *time.ParseError parsing time "2020-10-07 12:59:45.313096 +0100 BST m=+9.512675090" as "2006-01-02T15:04:05Z07:00": cannot parse " 12:59:45.313096 +0100 BST m=+9.512675090" as "T"
/home/hugo/src/gruntwork/cloud-nuke/aws/ecs_cluster.go:187 (0xb2c3fb)
        parseTimestampTag: return parsed, errors.WithStackTrace(err)
/home/hugo/src/gruntwork/cloud-nuke/aws/ecs_cluster.go:169 (0xb2c06d)
        getFirstSeenEcsClusterTag: firstSeenTime, err := parseTimestampTag(aws.StringValue(tag.Value))
/home/hugo/src/gruntwork/cloud-nuke/aws/ecs_cluster.go:75 (0xb2b072)
        getAllEcsClustersOlderThan: firstSeenTime, err := getFirstSeenEcsClusterTag(awsSession, clusterArn)
/home/hugo/src/gruntwork/cloud-nuke/aws/aws.go:369 (0xb21cff)
        GetAllResources: ecsClusterArns, err := getAllEcsClustersOlderThan(session, region, excludeAfter)
/home/hugo/src/gruntwork/cloud-nuke/commands/cli.go:224 (0xb42e38)
        awsNuke: account, err := aws.GetAllResources(targetRegions, *excludeAfter, resourceTypes, configObj)
/home/hugo/src/go/pkg/mod/github.com/gruntwork-io/gruntwork-cli@v0.1.2/errors/errors.go:93 (0xa7519e)
        WithPanicHandling.func1: return action(context)
/home/hugo/src/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 (0xa64dc2)
        HandleAction: return a(context)
/home/hugo/src/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 (0xa65fdb)
        Command.Run: err = HandleAction(c.Action, context)
/home/hugo/src/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 (0xa63068)
        (*App).Run: return c.Run(context)
/home/hugo/src/go/pkg/mod/github.com/gruntwork-io/gruntwork-cli@v0.1.2/entrypoint/entrypoint.go:21 (0xb45498)
        RunApp: err := app.Run(os.Args)
/home/hugo/src/gruntwork/cloud-nuke/main.go:13 (0xb456c7)
        main: entrypoint.RunApp(app)
/usr/local/go/src/runtime/proc.go:225 (0x43a276)
        main: fn()
/usr/local/go/src/runtime/asm_amd64.s:1371 (0x46d321)
        goexit: BYTE    $0x90   // NOP
  error="parsing time \"2020-10-07 12:59:45.313096 +0100 BST m=+9.512675090\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \" 12:59:45.313096 +0100 BST m=+9.512675090\" as \"T\""
```

Note that this happened at the listing phase, when cloud-nuke is finding the resources to delete.

**Comment by hongil0316** [comment] 2023-10-25 23:39
Cannot reproduce this issue. Closing this issue since it has been longer than 2 years.

**Closed by hongil0316** 2023-10-25 23:39 UTC
Labels: bug, p:queued
