### ISSUE TITLE
Investigate EKS autoscaling groups deletion behavior

### ISSUE THREAD

**Issue by zackproser** [gruntwork-io/cloud-nuke#339] opened 2022-08-01 17:16 UTC
As observed with @pete0emerson today, EKS ASG's can take upwards of 10 minutes to delete with 4 instances. ECS was much quicker. What's the difference here?

**Comment by yorinasub17** [comment] 2022-08-01 17:29
I suspect the issue is because for EKS, you need to tear down a dedicated resource (Managed Node Groups), which has more resources tied to it than just the ASG. I don't think there isn't anything we can do here - there's just more stuff that AWS needs to manage (and thus destroy) for EKS.

**Comment by zackproser** [comment] 2022-08-01 17:35
Great, thanks for that context @yorinasub17!

**Comment by yorinasub17** [comment] 2022-08-01 17:38
Going to close this given the context.

**Closed by yorinasub17** 2022-08-01 17:38 UTC
