### ISSUE TITLE
Feature: Add support for GuardDuty Detectors

### ISSUE THREAD

**Issue by zackproser** [gruntwork-io/cloud-nuke#321] opened 2022-07-06 22:06 UTC
Implement support for inspecting and nuking GuardDuty Detectors, which in turn deletes all findings.

**Comment by yorinasub17** [comment] 2022-07-07 01:23
Duplicate of https://github.com/gruntwork-io/cloud-nuke/issues/175

**Closed by yorinasub17** 2022-07-07 01:23 UTC
