### ISSUE TITLE
Cloud nuke does n't support cleaning IAM policies by using config.yaml

### ISSUE THREAD

**Issue by abhishekmahajan0709222** [gruntwork-io/cloud-nuke#470] opened 2023-06-07 19:57 UTC
Cloud nuke latest version doesn't support nuking IAM policies using latest cloud nuke version

**Comment by hongil0316** [comment] 2023-06-09 23:42
Hey @abhishekmahajan0709222, thanks for reporting the issue you are seeing. Can you share a bit more details with your finding? 

* What version are you referring to? 
* Can you share your config.yaml file? 
* What would be the steps to reproduce the behaviour you are seeing?

**Comment by hongil0316** [comment] 2023-09-10 16:39
Closing this since we haven't received any response in a while.

**Closed by hongil0316** 2023-09-10 16:39 UTC
