### ISSUE TITLE
AWS SSO (Identity Center) profile errors with "missing required configuration: sso_region, sso_start_url"

### ISSUE THREAD

**Issue by hertzsprung** [gruntwork-io/cloud-nuke#487] opened 2023-07-01 19:33 UTC
I use `aws --profile admin sso login` to authenticate with AWS.
`aws --profile admin sts get-caller-identity` successfully reports `arn:aws:sts::123456789012:assumed-role/AWSReservedSSO_AdministratorAccess_xxx/admin`.  All aws-cli commands work fine, as does CDK.

But cloud-nuke reports:
```
ERRO[2023-07-01T20:24:31+01:00] profile "admin" is configured to use SSO but is missing required configuration:
sso_region, sso_start_url  binary=cloud-nuke version=v0.31.2
```

My `./aws/config` is autogenerated by `aws configure` and looks like this:
```
[default]
region = eu-west-1
sso_session = default-sso
sso_account_id = 123456789012
sso_role_name = PowerUserAccess
[profile admin]
region = eu-west-1
sso_session = default-sso
sso_account_id = 123456789012
sso_role_name = AdministratorAccess
[sso-session default-sso]
sso_start_url = https://d-1234567890.awsapps.com/start
sso_region = eu-west-1
sso_registration_scopes = sso:account:access
```

I've tried to copy-and-paste `sso_region` and `sso_start_url` into `[profile admin]` (even though I shouldn't need to), then I get a different error:
```
ERRO[2023-07-01T20:24:01+01:00] could not find any enabled regions            binary=cloud-nuke version=v0.31.2
```

I've tried exporting `AWS_PROFILE`, `AWS_REGION`, `AWS_DEFAULT_REGION`, and `AWS_SDK_LOAD_CONFIG=true` but see the same error.

**Comment by hongil0316** [comment] 2023-08-25 01:25
Hey @hertzsprung, have you tried using `aws-vault` with the profile. The command would look something like this once you configured the profile properly

aws-vault exec <profile_name> -- cloud-nuke command...

**Comment by hongil0316** [comment] 2023-09-10 03:32
Since we haven't received any response, we will close this ticket for now. Please re-open or recreate the issue if you have any further concern or issues.

**Closed by hongil0316** 2023-09-10 03:32 UTC

**Comment by jakub-pietrzak** [comment] 2023-10-13 15:01
@hongil0316 there is no issue when running this via `aws-vault`.
However plain `cloud-nuke` fails to utilize `sso-session` from the config.

It looks similar to the issues I faced with terraform or packer
* https://github.com/hashicorp/packer-plugin-amazon/issues/350
* https://github.com/hashicorp/terraform/issues/32465

And the solution there was to bump AWS SDK.

**Comment by hertzsprung** [comment] 2023-10-13 19:24
Confirmed this is working in the latest source build (57df2d5)

**Comment by hongil0316** [comment] 2023-10-13 23:29
Hey @jakub-pietrzak, you continue to see the issue? Can you explain why we can reproduce the same issue?

**Comment by jakub-pietrzak** [comment] 2023-10-14 03:54
@hongil0316 I have now checked and also confirm that this is working fine in the latest source build.

```
go run main.go aws --dry-run --region eu-central-1
```

The same however does not work in 0.32.0.
