### ISSUE TITLE
FatalError{Underlying: NatGatewayNotFound: NAT gateway nat-01234567890abcdef was not found

### ISSUE THREAD

**Issue by AlainODea** [gruntwork-io/cloud-nuke#292] opened 2022-04-06 21:07 UTC
When trying to delete a NAT Gateway, if it is already gone, there is no need to retry.

**Comment by hongil0316** [comment] 2023-10-01 23:58
Cannot reproduce error. Closing this issue for now. Please reach out with steps to reproduce if you continue experience issue.

**Closed by hongil0316** 2023-10-01 23:58 UTC
Labels: bug, p:needs triage
