### ISSUE TITLE
Feature request - delete resource in a specific region

### ISSUE THREAD

**Issue by mrrajeshrai** [gruntwork-io/cloud-nuke#70] opened 2019-09-19 19:41 UTC
Hi Team,

Are you planning to add include-region flag anytime soon? which can be used to delete resources in a specific region. 

Thanks

**Comment by autero1** [comment] 2019-09-20 05:28
Hi @mrrajeshrai, I believe this is a duplicate of #55, so closing this. A PR would be very welcome!

**Closed by autero1** 2019-09-20 05:28 UTC
Labels: duplicate

**Comment by saurabh-hirani** [comment] 2019-09-21 10:08
@autero1 @mrrajeshrai - raised https://github.com/gruntwork-io/cloud-nuke/pull/71 for the above.
