### ISSUE TITLE
Failure to Nuke VPC

### ISSUE THREAD

**Issue by james03160927** [gruntwork-io/cloud-nuke#805] opened 2024-12-09 01:52 UTC
Seeing failures to nuke VPC with network interface issues. 

```
Nuking batch of 2 vpc resource(s) in eu-west-1 [10/2551]  0% | 10sINFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 1 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 2 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 3 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 4 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 5 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 6 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 7 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 8 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 9 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 10 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 11 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 12 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 13 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 14 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 15 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 16 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 17 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 18 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 19 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 20 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 21 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 22 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 23 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 24 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 25 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 26 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 27 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 28 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 29 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 30 of 30. Sleeping for 10s and will retry. 
INFO[1929] Waiting for all Network interfaces to be deleted. 
INFO[1929] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 31 of 30. Sleeping for 10s and will retry. 
  DEBUG   Error waiting up Network interfaces deletion for VPC vpc-034873416314364b7: 'Waiting for all Network interfaces to be deleted.' unsuccessful after 30 retries
  ERROR   Failed to nuke vpc with err: 'Waiting for all Network interfaces to be deleted.' unsuccessful after 30 retries
  DEBUG   Describing load balancers for vpc-03526c24dfc77f764                   
  DEBUG   Found 0 Endpoint services attached with the load balancers to nuke.   
  DEBUG   Successfully deleted he endpoints attached with load balancers for vpc-03526c24dfc77f764
  DEBUG   Successfully deleted loadbalancers attached vpc-03526c24dfc77f764     
  DEBUG   Describing target groups for vpc-03526c24dfc77f764                    
  DEBUG   Successfully deleted target group attached vpc-03526c24dfc77f764      
  DEBUG   Describing instances for vpc-03526c24dfc77f764                        
  DEBUG   Successfully deleted instances for vpc-03526c24dfc77f764              
  DEBUG   Start nuking VPC vpc-03526c24dfc77f764                                
  DEBUG   Successfully found DHCP option associated with VPC: default.          
  DEBUG   No DHCP options to nuke. DHCP already set to default.                 
  DEBUG   Start nuking route tables for vpc: vpc-03526c24dfc77f764              
  DEBUG   Found 1 route tables.                                                 
  DEBUG   Skipping main route table: rtb-0838b59a05f06a554                      
  DEBUG   Start nuking network interfaces for vpc: vpc-03526c24dfc77f764        
  DEBUG   Found 2 Elastic Network Interfaces to Nuke.                           
  DEBUG   Skipping network interface eni-001e6067dab2b4dc4 as it is in use      
  DEBUG   Skipping network interface eni-0356ec1f96077c675 as it is in use      
  DEBUG   Found 0 NAT gateways to delete                                        
  DEBUG   Successfully deleted NAT gateways for vpc vpc-03526c24dfc77f764       
  DEBUG   Start nuking Egress Only Internet Gateways for vpc: vpc-03526c24dfc77f764
  DEBUG   Found 0 Egress Only Internet Gateways to nuke.                        
  DEBUG   Successfully deleted Egress Only Internet Gateways for vpc-03526c24dfc77f764
Nuking batch of 2 vpc resource(s) in eu-west-1 [10/2551]  0% | 5m26sINFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 1 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 2 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 3 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 4 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 5 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 6 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 7 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 8 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 9 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 10 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 11 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 12 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 13 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 14 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 15 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 16 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 17 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 18 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 19 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 20 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 21 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 22 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 23 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 24 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 25 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 26 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 27 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 28 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 29 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 30 of 30. Sleeping for 10s and will retry. 
INFO[2245] Waiting for all Network interfaces to be deleted. 
INFO[2245] Waiting for all Network interfaces to be deleted. returned an error: Not all Network interfaces are deleted.. Attempt 31 of 30. Sleeping for 10s and will retry. 
  DEBUG   Error waiting up Network interfaces deletion for VPC vpc-03526c24dfc77f764: 'Waiting for all Network interfaces to be deleted.' unsuccessful after 30 retries
  ERROR   Failed to nuke vpc with err: 'Waiting for all Network interfaces to be deleted.' unsuccessful after 30 retries
  DEBUG   Terminating 4 awsResource in batches                                  
  DEBUG   Deleting all network interface in region eu-west-1                    41s
  DEBUG   Detaching network interface eni-00e320de5c130f30d from instances      41s
  DEBUG   Releasing Elastic IP address(s) associated on instance                41s
Nuking batch of 4 network-interface resource(s) in eu-west-1 [12/2551]  0% | 10m41sERRO[2024-12-09T01:36:02Z] runtime error: invalid memory address or nil pointer dereference  binary=cloud-nuke version=44ffa251c91ea876bf78dcb18d6ff1219e16bece
```

**Comment by wakeful** [comment] 2024-12-09 07:42
hey, @james03160927 

Is the code for the environment you are nuking in a public repository?

From the error log, it looks like we should also add a guard or a nil check in this function:

```go
func (ni *NetworkInterface) releaseEIPs(instance *string) error {
	logging.Debugf("Releasing Elastic IP address(s) associated on instance %s", awsgo.ToString(instance))
	// get the elastic ip's associated with the EC2's
```

It looks like a cache problem with the **AWS API endpoint**. We are calling the function above from here, 
but I’m struggling to reproduce the behaviour where `networkInterface.Attachment.InstanceId` is nil.

```go
func (ni *NetworkInterface) detachNetworkInterface(id *string) error {
...
	for _, networkInterface := range output.NetworkInterfaces {

		// check there has some attachments
		if networkInterface.Attachment == nil {
			continue
		}

		if err := ni.nukeInstance(networkInterface.Attachment.InstanceId); err != nil {	
```

**Comment by james03160927** [comment] 2024-12-10 00:19
We are using `cloud-nuke` to clean up resources created for testing. It seems like I cannot really reproduce the issue but the first step is to add those `null` checks to prevent nil pointer issues. 

Can you elaborate what you mean by "cache problem? 
> It looks like a cache problem with the AWS API endpoint.

**Comment by wakeful** [comment] 2024-12-10 08:10
> Can you elaborate what you mean by "cache problem?
> 
> > It looks like a cache problem with the AWS API endpoint.

I meant maybe it’s a caching problem. _The interfaces are still marked as in use_, but they may no longer actually be in use. It’s hard to say without a concrete example or access to the environment where it failed - AWS API endpoints can sometimes be quite slow to update.

**Closed** 2024-12-15 15:47 UTC
