### ISSUE TITLE
ECS service delete does not handle daemon tasks correctly

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/cloud-nuke#219] opened 2021-10-13 15:12 UTC
We are seeing the following nuke error in our pipeline:

```
[cloud-nuke] ERRO[2021-10-13T15:09:52Z] [Failed] Failed to drain service arn:aws:ecs:us-west-2:000000000:service/test-cluster4NyJS8/test-daemon-service4NyJS8: InvalidParameterException: The daemon scheduling strategy does not support a desired count for services. Remove the desired count value and try again 
[cloud-nuke] INFO[2021-10-13T15:09:52Z] [OK] 0 of 1 ECS service(s) deleted in us-west-2 
[cloud-nuke] INFO[2021-10-13T15:09:52Z] Terminating 8 resources in batches           
[cloud-nuke] INFO[2021-10-13T15:09:52Z] Deleting 8 ECS clusters in region us-west-2  
[cloud-nuke] ERRO[2021-10-13T15:09:52Z] Error, failed to delete cluster with ARN arn:aws:ecs:us-west-2:000000000:cluster/test-cluster4NyJS8
```

**Comment by hongil0316** [comment] 2023-11-13 00:10
This bug is no longer relevant and has been more than 2 years. Cannot reproduce so closing this issue.

**Closed** 2023-11-13 00:10 UTC
Labels: bug
