### ISSUE TITLE
Access Denied deleting config rules

### ISSUE THREAD

**Issue by ellisonc** [gruntwork-io/cloud-nuke#410] opened 2023-02-07 15:10 UTC
<img width="1062" alt="Screenshot 2023-02-07 at 9 09 03 AM" src="https://user-images.githubusercontent.com/12515168/217283405-eff2bbba-05cb-4123-969a-063ac85903a5.png">
Error messages get cut off in the table view and there's no way to view the full message.  I believe I should have access to these config rules, but nuke doesn't want to remove them.

**Comment by jgrant-sms** [comment] 2023-03-06 18:45
I ran in to the same issue, disabling Security Hub removed the config service rules from my account.

**Comment by marinalimeira** [comment] 2023-03-30 10:30
+1, I am running into this error too!

**Comment by hongil0316** [comment] 2023-09-20 02:41
Cannot reproduce the same issue right now. Looking into it though. 

It seems like there's another related issue looking at this error message: 

```
❌ ResourceInUseException: The rule iam-user-unused-credentials-check currently has a RemediationConfiguration. Please delete the RemediationConfiguration and try again.
```

It seems like we need to also remove `RemediationConfiguration` if a config rule has it.

**Comment by hongil0316** [comment] 2023-11-03 14:18
Closing this issue as we cannot reproduce this error.

**Closed by hongil0316** 2023-11-03 14:18 UTC
Labels: bug
