### ISSUE TITLE
Gruntwork test ACM certificate getting removed in `us-west-1` and `eu-west-2`

### ISSUE THREAD

**Issue by arsci** [gruntwork-io/cloud-nuke#579] opened 2023-09-05 16:13 UTC
The wildcard ACM certificate used for testing in `phxdevops` is getting removed by the scheduled `cloud-nuke` job, but only in `us-west-1` and `eu-west-2` regions. We need this key to be present in these two regions for tests. 

I haven't had a chance to dig in to see if we are using a config exclusion, and it isn't working, or if there is some other reason for the removal. It appears to be only these two regions, the key does not get deleted in other regions.

**Comment by gcagle3** [comment] 2023-09-05 19:01
Temporarily disabled tests for these regions in terraform-aws-load-balancer (via [this commit](https://github.com/gruntwork-io/terraform-aws-load-balancer/commit/a866d1e264969bae4c9f4ca6009d1280fde74d41#diff-5ba489a7a4589e939a41182fd4fcb058b06dd85a62c86317e07faa56d800378cL24)) to minimize test failures. Leaving a note here as a reminder to re-enable these regions once this issue is resolved.

**Comment by hongil0316** [comment] 2023-09-07 17:02
Looked at the existing configuration and it doesn't seem to have any filtering for ACM resource type - https://github.com/gruntwork-io/cloud-nuke/blob/master/.circleci/nuke_config.yml.

**Comment by hongil0316** [comment] 2023-09-07 17:02
Also, we don't pass in ACM as the exclude resource type - https://github.com/gruntwork-io/cloud-nuke/blob/master/.circleci/config.yml#L45.

**Comment by hongil0316** [comment] 2023-09-07 17:03
It seems like the ACM for gruntwork testing seems to have domain name *.gruntwork.in so we can create a filter for that 

<img width="1039" alt="image" src="https://github.com/gruntwork-io/cloud-nuke/assets/96548424/c297b38f-b7f0-4990-9fce-fc401b601a0a">

**Comment by hongil0316** [comment] 2023-09-07 17:07
It seems like we have an additional filter to exclude resources that are currently being used. However, I guess the certificates in those regions were not being used for some region?

**Comment by hongil0316** [comment] 2023-09-07 17:57
Hey @arsci, I created certificates in both `us-west-1` and `eu-west-2` regions. I'm not sure if creating certificates solves the test failures. I'll leave this ticket open until we verify whether tests pass again.

**Comment by arsci** [comment] 2023-09-07 21:08
Thanks @hongil0316! Yes, just creating those certs should solve the tests errors. 

@gcagle3 you can re-enable tests for your branch in those two regions

**Comment by gcagle3** [comment] 2023-09-14 13:59
> @gcagle3 you can re-enable tests for your branch in those two regions

These have been re-enabled. Thanks!

**Comment by hongil0316** [comment] 2023-09-14 22:29
Nice. I'll close this issue then!

**Comment by gcagle3** [comment] 2023-09-15 16:40
> It seems like the ACM for gruntwork testing seems to have domain name *.gruntwork.in so we can create a filter for that
> 
> <img alt="image" width="1039" src="https://user-images.githubusercontent.com/96548424/266390291-c297b38f-b7f0-4990-9fce-fc401b601a0a.png">

@hongil0316 would it be possible to add a filter for the domain name 'gruntwork.in' as well? It looks like we'll need ACM certs for both '*.gruntwork.in' and 'gruntwork.in' for all of the load balancer tests to complete. 

Example:
![image](https://github.com/gruntwork-io/cloud-nuke/assets/81821730/b78a24f1-33bb-499e-9807-1ff160cfc1c6)

We'll need this for the following regions (if the filter is region specific, if not no worries):

- us-east-1
- us-east-2
- us-west-1
- us-west-2
- eu-west-1
- eu-west-2

**Comment by hongil0316** [comment] 2023-09-15 19:33
I believe this change should cover both scenarios: 

https://github.com/gruntwork-io/cloud-nuke/pull/580/files

**Comment by gcagle3** [comment] 2023-09-15 20:06
Ah, that should work, splendid. Thank you, I'll re-close this one!

**Comment by gcagle3** [comment] 2023-09-22 14:44
@hongil0316 hm, some bad news. It looks like the certificates for just 'gruntworks.in' (not *.gruntworks.in) are still being deleted every night. 

As a thought, should the 'include' in this code actually be exclude? 

```
ACM:
  include:
    names_regex:
      - "^gruntwork.in"
```

**Comment by hongil0316** [comment] 2023-10-05 01:02
Hey @gcagle3 @arsci, I just tested the `cloud-nuke` behaviour with the circleCi `nuke_config.yml` and it seems to work as expected. This is the command line I used: 

```
aws-vault exec phxdevops -- go run main.go aws --resource-type acm --log-level debug --region us-east-1 --config .circleci/nuke_config.yml
```

And here is the debugging lines: 
![image](https://github.com/gruntwork-io/cloud-nuke/assets/96548424/7ee0c4d4-5db1-4f9d-9fe5-4b1085493d58)


![image](https://github.com/gruntwork-io/cloud-nuke/assets/96548424/60fa3bd6-dfcf-40bb-ab43-384d7b2ba59a)

**Comment by hongil0316** [comment] 2023-10-05 01:04
Looking at the CloudTrail activies, it seems to be deleted by the `circle-ci-test` user name

![image](https://github.com/gruntwork-io/cloud-nuke/assets/96548424/0b6155f6-612f-4ee0-aa46-67bb79adc4c5)

**Comment by hongil0316** [comment] 2023-10-05 01:13
From this execution, I verified that it seems to be indeed deleted by circle ci - https://app.circleci.com/pipelines/github/gruntwork-io/cloud-nuke/12355/workflows/ac53f08b-cbbe-41b8-8f58-3eaadbb781d9/jobs/34125. 

![image](https://github.com/gruntwork-io/cloud-nuke/assets/96548424/96ae9f8f-35ef-4d67-84ef-36cab829417e)

**Comment by hongil0316** [comment] 2023-10-05 01:14
Hey @arsci @gcagle3, can you tell me how you are creating the ACM? Maybe the way I create the ACM is not the same as those certificates being created for unit tests? 

This is how I created: 

![image](https://github.com/gruntwork-io/cloud-nuke/assets/96548424/bd2e1d53-f5b0-4a41-a55d-12970d70460a)

**Comment by gcagle3** [comment] 2023-10-05 13:14
> Hey @arsci @gcagle3, can you tell me how you are creating the ACM? Maybe the way I create the ACM is not the same as those certificates being created for unit tests?
> 
> This is how I created:
> 
> ![image](https://user-images.githubusercontent.com/96548424/272752523-bd2e1d53-f5b0-4a41-a55d-12970d70460a.png)

This is exactly the same process I've been using for both gruntwork.in and *.gruntwork.in.

**Comment by hongil0316** [comment] 2023-10-10 22:15
Hmm the debug message doesn't seem to help too much... I wonder if the config file values are being reflected properly. 
The odd thing is that we are having different behaviour when running in circleCi vs. locally...

**Comment by gcagle3** [comment] 2023-10-11 19:38
> The odd thing is that we are having different behaviour when running in circleCi vs. locally...

Would CircleCi be setting specific environment variables that would change the behavior?

**Comment by hongil0316** [comment] 2023-10-13 00:51
Looking at the debug logs, it seems like the config is not properly parsed for whatever reason: 

```
  DEBUG   shouldInclude result for ACM: arn:aws:acm:us-west-1:087285199408:certificate/1fc80fe9-5bcf-43d9-86c1-e5a6d3d6ffd9 w/ domain name: gruntwork.in, time: 2023-10-11 19:46:05.48 +0000 UTC, and config: {IncludeRule:{NamesRegExp:[] TimeAfter:<nil> TimeBefore:<nil> Tag:<nil>} ExcludeRule:{NamesRegExp:[] TimeAfter:2023-10-11 19:52:45.931855658 +0000 UTC m=-7198.437556645 TimeBefore:<nil> Tag:<nil>}}
```

You will notice that `NamesRegExp` for both `IncludeRule` and `ExcludeRule` are empty.

**Comment by gcagle3** [comment] 2023-10-13 22:05
After internal discussion, we're wondering if the [default tests](https://github.com/gruntwork-io/cloud-nuke/blob/master/.circleci/config.yml#L16-L35) (which run with no config) might be causing this. Looking at the test, it will check if the cert is in use and try to delete if it is not in use. 

Comparing the above against the following we've observed:

- In us-east-1, us-east-2, us-west-2, and eu-west-1, the '[gruntwork.in](http://gruntwork.in/)' cert was deleted
- In us-west-1 and eu-west-2, both the '[gruntwork.in](http://gruntwork.in/)' and '*.[gruntwork.in](http://gruntwork.in/)' certs were deleted

It is important to note that the '*.[gruntwork.in](http://gruntwork.in/)' cert is 'in use' in the us-east-1, us-east-2, us-west-2 and eu-west-1 regions where it is not being deleted. It is not in use in us-west-1 / eu-west-2 where it is being deleted, which would make sense if the tests are actually deleting the certs. All certs being deleted are _not_ in use. 

@hongil0316 do you think it might be worth adjusting the test case to address this?

**Comment by hongil0316** [comment] 2023-10-17 21:28
Had further discussion internally here: https://gruntwork-io.slack.com/archives/C6V3DJAHJ/p1697159092430149
We initially mitigated the issue by excluding ACM resource type - https://github.com/gruntwork-io/cloud-nuke/pulls?q=is%3Apr+is%3Aclosed. 

After further troubleshooting, I realized that the bug existed when we had both config file + time filter present at the same time. Here is a fix for the bug - https://github.com/gruntwork-io/cloud-nuke/pull/607

**Closed** 2023-10-17 22:02 UTC

**Comment by gcagle3** [comment] 2023-10-23 17:04
As a quick follow-up, I can confirm that both the *.gruntwork.in and gruntwork.in certificate have not been deleted (and are still present) since this PR was merged. Great work on this @hongil0316!
